-- MySQL Script generated by MySQL Workbench
-- Thu Oct  6 14:07:52 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Pytania`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pytania` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pytania` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Treść` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Odpowiedzi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Odpowiedzi` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Odpowiedzi` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Treść` VARCHAR(45) NULL,
  `Poprawna` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pytania_has_Odpowiedzi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pytania_has_Odpowiedzi` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pytania_has_Odpowiedzi` (
  `Pytania_id` INT NOT NULL,
  `Odpowiedzi_id` INT NOT NULL,
  PRIMARY KEY (`Pytania_id`, `Odpowiedzi_id`),
  CONSTRAINT `fk_Pytania_has_Odpowiedzi_Pytania`
    FOREIGN KEY (`Pytania_id`)
    REFERENCES `mydb`.`Pytania` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pytania_has_Odpowiedzi_Odpowiedzi1`
    FOREIGN KEY (`Odpowiedzi_id`)
    REFERENCES `mydb`.`Odpowiedzi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OdpowiedziUczniow`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`OdpowiedziUczniow` ;

CREATE TABLE IF NOT EXISTS `mydb`.`OdpowiedziUczniow` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Treść` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Uczniowie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Uczniowie` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Uczniowie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Imie` VARCHAR(45) NULL,
  `Nazwisko` VARCHAR(45) NULL,
  `OdpowiedziUczniow_id` INT NOT NULL,
  PRIMARY KEY (`id`, `OdpowiedziUczniow_id`),
  CONSTRAINT `fk_Uczniowie_OdpowiedziUczniow1`
    FOREIGN KEY (`OdpowiedziUczniow_id`)
    REFERENCES `mydb`.`OdpowiedziUczniow` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
